---
cog_bundle_version: 4

name: s3
version: 0.1.0
description: Manage S3 buckets and files
homepage: https://github.com/cogcmd/aws-s3
author: Patrick Van Stee <patrick@operable.io>
commands:
  bucket-acl:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
    options:
      region:
        type: string
        required: false
        description: S3 location to connect to (us-east-1, us-east-2, us-west-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, ap-northeast-2, ap-south-1, sa-east-1)
        short_flag: r
  bucket-list:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
    options:
      region:
        type: string
        required: false
        description: S3 location to connect to (us-east-1, us-east-2, us-west-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, ap-northeast-2, ap-south-1, sa-east-1)
        short_flag: r
  bucket-create:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
    options:
      acl:
        type: string
        required: false
        description: ACL to apply. Defaults to private. (private, public-read, public-read-write, authenticated-read)
        short_flag: a
      region:
        type: string
        required: false
        description: S3 location in which to create the bucket (us-east-1, us-east-2, us-west-1, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, ap-northeast-2, ap-south-1, sa-east-1)
        short_flag: r
  bucket-destroy:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
  file-list:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
  file-create:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
  file-info:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
  file-destroy:
    executable: /Users/vanstee/Code/cogcmd/aws-s3/cog-command
    rules:
      - allow
templates:
  bucket_list:
    body: |
      | Name | Creation Date |
      | ---- | ------------- |
      ~each var=$results as=bucket~
      | ~$bucket.name~ | ~$bucket.creation_date~ |
      ~end~
  bucket_create:
    body: |
      ~each var=$results as=bucket~
      Created bucket at location ~$bucket.location~
      ~end~
  bucket_destroy:
    body: |
      ~each var=$results as=bucket~
      Destroyed bucket ~$bucket.name~
      ~end~
  bucket_acl:
    body: |
      | Permission | Grantee |
      | ---- | ------------- |
      ~each var=$results as=acl~
      | ~$acl.permission~ | ~$acl.grantee.display_name~ |
      ~end~
  file_list:
    body: |
      | Key | Last Modified | Size |
      | --- | ------------- | ---- |
      ~each var=$results as=file~
      | ~$file.key~ | ~$file.last_modified~ | ~$file.size~ |
      ~end~
  file_create:
    body: |
      ~each var=$results as=file~
      Created file ~$file.key~ in bucket ~$file.bucket~
      ~end~
  file_info:
    body: |
      ~each var=$results as=file~
      Contents of file ~$file.key~ in bucket ~$file.bucket~
      ```
      ~$file.body~
      ```
      ~end~
  file_destroy:
    body: |
      ~each var=$results as=file~
      Destroyed file ~$file.key~ in bucket ~$file.bucket~
      ~end~
